import type { Metadata } from "next";
import "../globals.css";
import { unstable_setRequestLocale } from "next-intl/server";
import { availableLocaleCodes } from "@/next.locales.mjs";
import { Link } from "@/navigation.mjs";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import LanguageDropdown from "@/components/layout/locale-dropdown";
import { ThemeProvider } from "@/providers/theme-provider";
import WithNavBar from "@/components/with-nav-bar";
import { LocaleProvider } from "@/providers/locale-provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const dynamicParams = false;

export function generateStaticParams() {
  return availableLocaleCodes.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <LocaleProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <WithNavBar />
            {children}
          </ThemeProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}
